apiVersion: v1 # This is the API version for the Kubernetes Secret resource.
kind: Secret # This specifies that the resource being defined is a Secret.
metadata:
  name: postgres-secret # name of the Secret, which can be referenced by other resources (like Deployments) to access the secret data.
type: Opaque # type: Opaque is a generic secret type
stringData: # secret value  is provided in plain text below but will be encoded in Kubernetes
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: postgres
  POSTGRES_DB: matchafinder