apiVersion: apps/v1
kind: Deployment
metadata:
  name: shop-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shop-service
  template:
    metadata:
      labels:
        app: shop-service
    spec:
      containers:
      - name: shop-service
        # for local development, you can use the following line to reference the image built locally:
        #image: shop-service:1.0 # This is the name and tag of the Docker image for the shop-service container
        #imagePullPolicy: IfNotPresent # This policy tells Kubernetes to pull the image only if it is not already present on the node

        # For AWS ECR, you would replace the image field with the following line, using your actual AWS account ID, region, and repository name:
        # replace YOUR_AWS_ACCOUNT_ID, YOUR_REGION, and matcha-shop-service with your actual values
        image: YOUR_AWS_ACCOUNT_ID.dkr.ecr.YOUR_REGION.amazonaws.com/matcha-shop-service:latest # This is the name and tag of the Docker image for the shop-service container in AWS ECR
        imagePullPolicy: Always

        ports:
        - containerPort: 8081
        env:
        - name: SPRING_PROFILES_ACTIVE
          valueFrom:
            configMapKeyRef:
              name: shop-service-config
              key: SPRING_PROFILE
        - name: DATABASE_HOST
          valueFrom:
            configMapKeyRef:
              name: shop-service-config
              key: DATABASE_HOST
        - name: DATABASE_PORT
          valueFrom:
            configMapKeyRef:
              name: shop-service-config
              key: DATABASE_PORT
        - name: DATABASE_NAME
          valueFrom:
            configMapKeyRef:
              name: shop-service-config
              key: DATABASE_NAME
        resources:
          requests:
            memory: "512Mi" # guaranteed minimum memory allocation for the container 512MB
            cpu: "500m" # guaranteed minimum CPU allocation for the container 500 millicores (0.5 CPU)
          limits:
            memory: "1Gi" # maximum memory allocation for the container 1GB
            cpu: "1000m" # maximum CPU allocation for the container 1000 millicores (1 CPU)
      
        
        